services:
  - type: web
    name: pythononline
    env: python
    region: frankfurt    # albo inny region
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
